name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Job to build the Docker image
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      #- name: Install dependencies
      #  run: |
      #    sudo apt-get update
      #    sudo apt-get install -y make

      - name: Run tests
        run: make test

      - name: Lint
        run: make lint

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build  .

      - uses: engineerd/setup-kind@v0.6.0
        with:
          version: "v0.24.0"
          skipClusterCreation: true

      - name: e2e
        run: make test-e2e

